
name: Main
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Install libvips
        run: apt install -y libvips-dev

      - name: Install poppler
        run: apt install -y poppler-utils

      - name: Install libreoffice
        run: apt install -y libreoffice libreoffice-core

      - name: Install ffmpeg
        run: apt install -y ffmpeg

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm install

      - name: Run tests
        run: npm test

