
name: Main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - name: Install libvips
        run: sudo apt-get install -y libvips-dev

      - name: Install libreoffice
        run: sudo apt-get install -y libreoffice

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm test

