
name: Test CI
on: [push]

env:
  - STATE:
    - success: ✅
    - failure: 🔴

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - name: Install libvips
        run: sudo apt-get install -y libvips-dev

      - name: Install poppler
        run: sudo apt-get install -y poppler-utils

      - name: Install libreoffice
        run: sudo apt-get install -y libreoffice libreoffice-core

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Notification
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.BOT_TOKEN }}
          to: ${{ secrets.CHAT_ID }}
          message: |
            ${{ env.STATE[job.status] }} ${{ github.actor }} created commit: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
